version: '3.8'

services:
  mdm-db:
    image: postgres:15-alpine
    container_name: mdm-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: mdm_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  mdm-core:
    build: ./mdm-core
    container_name: mdm-core
    depends_on:
      - mdm-db
    environment:
      - DATABASE_URL=postgresql://admin:supersecretpassword@mdm-db:5432/mdm_db

  # ADD THIS NEW SERVICE BLOCK BELOW:
  steward-ui:
    build: ./steward-ui
    container_name: steward-ui
    ports:
      - "8501:8501"
    depends_on:
      - mdm-db
    environment:
      - DATABASE_URL=postgresql://admin:supersecretpassword@mdm-db:5432/mdm_db

volumes:
  pgdata: